/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package firewall

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/networkfirewall"

	svcapitypes "github.com/crossplane/provider-aws/apis/networkfirewall/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeFirewallInput returns input for read
// operation.
func GenerateDescribeFirewallInput(cr *svcapitypes.Firewall) *svcsdk.DescribeFirewallInput {
	res := &svcsdk.DescribeFirewallInput{}

	if cr.Spec.ForProvider.FirewallName != nil {
		res.SetFirewallName(*cr.Spec.ForProvider.FirewallName)
	}

	return res
}

// GenerateFirewall returns the current state in the form of *svcapitypes.Firewall.
func GenerateFirewall(resp *svcsdk.DescribeFirewallOutput) *svcapitypes.Firewall {
	cr := &svcapitypes.Firewall{}

	if resp.Firewall != nil {
		f0 := &svcapitypes.Firewall_SDK{}
		if resp.Firewall.DeleteProtection != nil {
			f0.DeleteProtection = resp.Firewall.DeleteProtection
		}
		if resp.Firewall.Description != nil {
			f0.Description = resp.Firewall.Description
		}
		if resp.Firewall.FirewallArn != nil {
			f0.FirewallARN = resp.Firewall.FirewallArn
		}
		if resp.Firewall.FirewallId != nil {
			f0.FirewallID = resp.Firewall.FirewallId
		}
		if resp.Firewall.FirewallName != nil {
			f0.FirewallName = resp.Firewall.FirewallName
		}
		if resp.Firewall.FirewallPolicyArn != nil {
			f0.FirewallPolicyARN = resp.Firewall.FirewallPolicyArn
		}
		if resp.Firewall.FirewallPolicyChangeProtection != nil {
			f0.FirewallPolicyChangeProtection = resp.Firewall.FirewallPolicyChangeProtection
		}
		if resp.Firewall.SubnetChangeProtection != nil {
			f0.SubnetChangeProtection = resp.Firewall.SubnetChangeProtection
		}
		if resp.Firewall.SubnetMappings != nil {
			f0f8 := []*svcapitypes.SubnetMapping{}
			for _, f0f8iter := range resp.Firewall.SubnetMappings {
				f0f8elem := &svcapitypes.SubnetMapping{}
				if f0f8iter.SubnetId != nil {
					f0f8elem.SubnetID = f0f8iter.SubnetId
				}
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.SubnetMappings = f0f8
		}
		if resp.Firewall.Tags != nil {
			f0f9 := []*svcapitypes.Tag{}
			for _, f0f9iter := range resp.Firewall.Tags {
				f0f9elem := &svcapitypes.Tag{}
				if f0f9iter.Key != nil {
					f0f9elem.Key = f0f9iter.Key
				}
				if f0f9iter.Value != nil {
					f0f9elem.Value = f0f9iter.Value
				}
				f0f9 = append(f0f9, f0f9elem)
			}
			f0.Tags = f0f9
		}
		if resp.Firewall.VpcId != nil {
			f0.VPCID = resp.Firewall.VpcId
		}
		cr.Status.AtProvider.Firewall = f0
	} else {
		cr.Status.AtProvider.Firewall = nil
	}
	if resp.FirewallStatus != nil {
		f1 := &svcapitypes.FirewallStatus_SDK{}
		if resp.FirewallStatus.ConfigurationSyncStateSummary != nil {
			f1.ConfigurationSyncStateSummary = resp.FirewallStatus.ConfigurationSyncStateSummary
		}
		if resp.FirewallStatus.Status != nil {
			f1.Status = resp.FirewallStatus.Status
		}
		if resp.FirewallStatus.SyncStates != nil {
			f1f2 := map[string]*svcapitypes.SyncState{}
			for f1f2key, f1f2valiter := range resp.FirewallStatus.SyncStates {
				f1f2val := &svcapitypes.SyncState{}
				if f1f2valiter.Attachment != nil {
					f1f2valf0 := &svcapitypes.Attachment{}
					if f1f2valiter.Attachment.EndpointId != nil {
						f1f2valf0.EndpointID = f1f2valiter.Attachment.EndpointId
					}
					if f1f2valiter.Attachment.Status != nil {
						f1f2valf0.Status = f1f2valiter.Attachment.Status
					}
					if f1f2valiter.Attachment.SubnetId != nil {
						f1f2valf0.SubnetID = f1f2valiter.Attachment.SubnetId
					}
					f1f2val.Attachment = f1f2valf0
				}
				if f1f2valiter.Config != nil {
					f1f2valf1 := map[string]*svcapitypes.PerObjectStatus{}
					for f1f2valf1key, f1f2valf1valiter := range f1f2valiter.Config {
						f1f2valf1val := &svcapitypes.PerObjectStatus{}
						if f1f2valf1valiter.SyncStatus != nil {
							f1f2valf1val.SyncStatus = f1f2valf1valiter.SyncStatus
						}
						f1f2valf1[f1f2valf1key] = f1f2valf1val
					}
					f1f2val.Config = f1f2valf1
				}
				f1f2[f1f2key] = f1f2val
			}
			f1.SyncStates = f1f2
		}
		cr.Status.AtProvider.FirewallStatus = f1
	} else {
		cr.Status.AtProvider.FirewallStatus = nil
	}

	return cr
}

// GenerateCreateFirewallInput returns a create input.
func GenerateCreateFirewallInput(cr *svcapitypes.Firewall) *svcsdk.CreateFirewallInput {
	res := &svcsdk.CreateFirewallInput{}

	if cr.Spec.ForProvider.DeleteProtection != nil {
		res.SetDeleteProtection(*cr.Spec.ForProvider.DeleteProtection)
	}
	if cr.Spec.ForProvider.Description != nil {
		res.SetDescription(*cr.Spec.ForProvider.Description)
	}
	if cr.Spec.ForProvider.FirewallName != nil {
		res.SetFirewallName(*cr.Spec.ForProvider.FirewallName)
	}
	if cr.Spec.ForProvider.FirewallPolicyARN != nil {
		res.SetFirewallPolicyArn(*cr.Spec.ForProvider.FirewallPolicyARN)
	}
	if cr.Spec.ForProvider.FirewallPolicyChangeProtection != nil {
		res.SetFirewallPolicyChangeProtection(*cr.Spec.ForProvider.FirewallPolicyChangeProtection)
	}
	if cr.Spec.ForProvider.SubnetChangeProtection != nil {
		res.SetSubnetChangeProtection(*cr.Spec.ForProvider.SubnetChangeProtection)
	}
	if cr.Spec.ForProvider.SubnetMappings != nil {
		f6 := []*svcsdk.SubnetMapping{}
		for _, f6iter := range cr.Spec.ForProvider.SubnetMappings {
			f6elem := &svcsdk.SubnetMapping{}
			if f6iter.SubnetID != nil {
				f6elem.SetSubnetId(*f6iter.SubnetID)
			}
			f6 = append(f6, f6elem)
		}
		res.SetSubnetMappings(f6)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f7 := []*svcsdk.Tag{}
		for _, f7iter := range cr.Spec.ForProvider.Tags {
			f7elem := &svcsdk.Tag{}
			if f7iter.Key != nil {
				f7elem.SetKey(*f7iter.Key)
			}
			if f7iter.Value != nil {
				f7elem.SetValue(*f7iter.Value)
			}
			f7 = append(f7, f7elem)
		}
		res.SetTags(f7)
	}
	if cr.Spec.ForProvider.VPCID != nil {
		res.SetVpcId(*cr.Spec.ForProvider.VPCID)
	}

	return res
}

// GenerateDeleteFirewallInput returns a deletion input.
func GenerateDeleteFirewallInput(cr *svcapitypes.Firewall) *svcsdk.DeleteFirewallInput {
	res := &svcsdk.DeleteFirewallInput{}

	if cr.Spec.ForProvider.FirewallName != nil {
		res.SetFirewallName(*cr.Spec.ForProvider.FirewallName)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
