/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package firewall

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/networkfirewall"
	svcsdk "github.com/aws/aws-sdk-go/service/networkfirewall"
	svcsdkapi "github.com/aws/aws-sdk-go/service/networkfirewall/networkfirewalliface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/networkfirewall/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an Firewall resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Firewall in AWS"
	errUpdate        = "cannot update Firewall in AWS"
	errDescribe      = "failed to describe Firewall"
	errDelete        = "failed to delete Firewall"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Firewall)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Firewall)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeFirewallInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeFirewallWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateFirewall(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Firewall)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateFirewallInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateFirewallWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.Firewall != nil {
		f0 := &svcapitypes.Firewall_SDK{}
		if resp.Firewall.DeleteProtection != nil {
			f0.DeleteProtection = resp.Firewall.DeleteProtection
		}
		if resp.Firewall.Description != nil {
			f0.Description = resp.Firewall.Description
		}
		if resp.Firewall.FirewallArn != nil {
			f0.FirewallARN = resp.Firewall.FirewallArn
		}
		if resp.Firewall.FirewallId != nil {
			f0.FirewallID = resp.Firewall.FirewallId
		}
		if resp.Firewall.FirewallName != nil {
			f0.FirewallName = resp.Firewall.FirewallName
		}
		if resp.Firewall.FirewallPolicyArn != nil {
			f0.FirewallPolicyARN = resp.Firewall.FirewallPolicyArn
		}
		if resp.Firewall.FirewallPolicyChangeProtection != nil {
			f0.FirewallPolicyChangeProtection = resp.Firewall.FirewallPolicyChangeProtection
		}
		if resp.Firewall.SubnetChangeProtection != nil {
			f0.SubnetChangeProtection = resp.Firewall.SubnetChangeProtection
		}
		if resp.Firewall.SubnetMappings != nil {
			f0f8 := []*svcapitypes.SubnetMapping{}
			for _, f0f8iter := range resp.Firewall.SubnetMappings {
				f0f8elem := &svcapitypes.SubnetMapping{}
				if f0f8iter.SubnetId != nil {
					f0f8elem.SubnetID = f0f8iter.SubnetId
				}
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.SubnetMappings = f0f8
		}
		if resp.Firewall.Tags != nil {
			f0f9 := []*svcapitypes.Tag{}
			for _, f0f9iter := range resp.Firewall.Tags {
				f0f9elem := &svcapitypes.Tag{}
				if f0f9iter.Key != nil {
					f0f9elem.Key = f0f9iter.Key
				}
				if f0f9iter.Value != nil {
					f0f9elem.Value = f0f9iter.Value
				}
				f0f9 = append(f0f9, f0f9elem)
			}
			f0.Tags = f0f9
		}
		if resp.Firewall.VpcId != nil {
			f0.VPCID = resp.Firewall.VpcId
		}
		cr.Status.AtProvider.Firewall = f0
	} else {
		cr.Status.AtProvider.Firewall = nil
	}
	if resp.FirewallStatus != nil {
		f1 := &svcapitypes.FirewallStatus_SDK{}
		if resp.FirewallStatus.ConfigurationSyncStateSummary != nil {
			f1.ConfigurationSyncStateSummary = resp.FirewallStatus.ConfigurationSyncStateSummary
		}
		if resp.FirewallStatus.Status != nil {
			f1.Status = resp.FirewallStatus.Status
		}
		if resp.FirewallStatus.SyncStates != nil {
			f1f2 := map[string]*svcapitypes.SyncState{}
			for f1f2key, f1f2valiter := range resp.FirewallStatus.SyncStates {
				f1f2val := &svcapitypes.SyncState{}
				if f1f2valiter.Attachment != nil {
					f1f2valf0 := &svcapitypes.Attachment{}
					if f1f2valiter.Attachment.EndpointId != nil {
						f1f2valf0.EndpointID = f1f2valiter.Attachment.EndpointId
					}
					if f1f2valiter.Attachment.Status != nil {
						f1f2valf0.Status = f1f2valiter.Attachment.Status
					}
					if f1f2valiter.Attachment.SubnetId != nil {
						f1f2valf0.SubnetID = f1f2valiter.Attachment.SubnetId
					}
					f1f2val.Attachment = f1f2valf0
				}
				if f1f2valiter.Config != nil {
					f1f2valf1 := map[string]*svcapitypes.PerObjectStatus{}
					for f1f2valf1key, f1f2valf1valiter := range f1f2valiter.Config {
						f1f2valf1val := &svcapitypes.PerObjectStatus{}
						if f1f2valf1valiter.SyncStatus != nil {
							f1f2valf1val.SyncStatus = f1f2valf1valiter.SyncStatus
						}
						f1f2valf1[f1f2valf1key] = f1f2valf1val
					}
					f1f2val.Config = f1f2valf1
				}
				f1f2[f1f2key] = f1f2val
			}
			f1.SyncStates = f1f2
		}
		cr.Status.AtProvider.FirewallStatus = f1
	} else {
		cr.Status.AtProvider.FirewallStatus = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	return e.update(ctx, mg)

}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Firewall)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteFirewallInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteFirewallWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.NetworkFirewallAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.NetworkFirewallAPI
	preObserve     func(context.Context, *svcapitypes.Firewall, *svcsdk.DescribeFirewallInput) error
	postObserve    func(context.Context, *svcapitypes.Firewall, *svcsdk.DescribeFirewallOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.FirewallParameters, *svcsdk.DescribeFirewallOutput) error
	isUpToDate     func(*svcapitypes.Firewall, *svcsdk.DescribeFirewallOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.Firewall, *svcsdk.CreateFirewallInput) error
	postCreate     func(context.Context, *svcapitypes.Firewall, *svcsdk.CreateFirewallOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.Firewall, *svcsdk.DeleteFirewallInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.Firewall, *svcsdk.DeleteFirewallOutput, error) error
	update         func(context.Context, cpresource.Managed) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Firewall, *svcsdk.DescribeFirewallInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.Firewall, _ *svcsdk.DescribeFirewallOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.FirewallParameters, *svcsdk.DescribeFirewallOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.Firewall, *svcsdk.DescribeFirewallOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.Firewall, *svcsdk.CreateFirewallInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Firewall, _ *svcsdk.CreateFirewallOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.Firewall, *svcsdk.DeleteFirewallInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.Firewall, _ *svcsdk.DeleteFirewallOutput, err error) error {
	return err
}
func nopUpdate(context.Context, cpresource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
