ignore:
  resource_names:
    - AccessKey
    - AccountAlias
    - Group
    - InstanceProfile
    - LoginProfile
    - OpenIDConnectProvider
    - PolicyVersion
    - Policy
    - Role
    - SAMLProvider
    - ServiceSpecificCredential
    - User
    - VirtualMFADevice
