// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessDetail) DeepCopyInto(out *AccessDetail) {
	*out = *in
	if in.LastAuthenticatedTime != nil {
		in, out := &in.LastAuthenticatedTime, &out.LastAuthenticatedTime
		*out = (*in).DeepCopy()
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessDetail.
func (in *AccessDetail) DeepCopy() *AccessDetail {
	if in == nil {
		return nil
	}
	out := new(AccessDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessKey) DeepCopyInto(out *AccessKey) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessKey.
func (in *AccessKey) DeepCopy() *AccessKey {
	if in == nil {
		return nil
	}
	out := new(AccessKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessKeyLastUsed) DeepCopyInto(out *AccessKeyLastUsed) {
	*out = *in
	if in.LastUsedDate != nil {
		in, out := &in.LastUsedDate, &out.LastUsedDate
		*out = (*in).DeepCopy()
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessKeyLastUsed.
func (in *AccessKeyLastUsed) DeepCopy() *AccessKeyLastUsed {
	if in == nil {
		return nil
	}
	out := new(AccessKeyLastUsed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessKeyMetadata) DeepCopyInto(out *AccessKeyMetadata) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessKeyMetadata.
func (in *AccessKeyMetadata) DeepCopy() *AccessKeyMetadata {
	if in == nil {
		return nil
	}
	out := new(AccessKeyMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedPermissionsBoundary) DeepCopyInto(out *AttachedPermissionsBoundary) {
	*out = *in
	if in.PermissionsBoundaryARN != nil {
		in, out := &in.PermissionsBoundaryARN, &out.PermissionsBoundaryARN
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundaryType != nil {
		in, out := &in.PermissionsBoundaryType, &out.PermissionsBoundaryType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedPermissionsBoundary.
func (in *AttachedPermissionsBoundary) DeepCopy() *AttachedPermissionsBoundary {
	if in == nil {
		return nil
	}
	out := new(AttachedPermissionsBoundary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedPolicy) DeepCopyInto(out *AttachedPolicy) {
	*out = *in
	if in.PolicyARN != nil {
		in, out := &in.PolicyARN, &out.PolicyARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedPolicy.
func (in *AttachedPolicy) DeepCopy() *AttachedPolicy {
	if in == nil {
		return nil
	}
	out := new(AttachedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomServiceLinkedRoleParameters) DeepCopyInto(out *CustomServiceLinkedRoleParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomServiceLinkedRoleParameters.
func (in *CustomServiceLinkedRoleParameters) DeepCopy() *CustomServiceLinkedRoleParameters {
	if in == nil {
		return nil
	}
	out := new(CustomServiceLinkedRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityDetails) DeepCopyInto(out *EntityDetails) {
	*out = *in
	if in.LastAuthenticated != nil {
		in, out := &in.LastAuthenticated, &out.LastAuthenticated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityDetails.
func (in *EntityDetails) DeepCopy() *EntityDetails {
	if in == nil {
		return nil
	}
	out := new(EntityDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityInfo) DeepCopyInto(out *EntityInfo) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityInfo.
func (in *EntityInfo) DeepCopy() *EntityInfo {
	if in == nil {
		return nil
	}
	out := new(EntityInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorDetails) DeepCopyInto(out *ErrorDetails) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorDetails.
func (in *ErrorDetails) DeepCopy() *ErrorDetails {
	if in == nil {
		return nil
	}
	out := new(ErrorDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.GroupName != nil {
		in, out := &in.GroupName, &out.GroupName
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupDetail) DeepCopyInto(out *GroupDetail) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.GroupName != nil {
		in, out := &in.GroupName, &out.GroupName
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupDetail.
func (in *GroupDetail) DeepCopy() *GroupDetail {
	if in == nil {
		return nil
	}
	out := new(GroupDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceProfile) DeepCopyInto(out *InstanceProfile) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.InstanceProfileID != nil {
		in, out := &in.InstanceProfileID, &out.InstanceProfileID
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceProfile.
func (in *InstanceProfile) DeepCopy() *InstanceProfile {
	if in == nil {
		return nil
	}
	out := new(InstanceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginProfile) DeepCopyInto(out *LoginProfile) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginProfile.
func (in *LoginProfile) DeepCopy() *LoginProfile {
	if in == nil {
		return nil
	}
	out := new(LoginProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MFADevice) DeepCopyInto(out *MFADevice) {
	*out = *in
	if in.EnableDate != nil {
		in, out := &in.EnableDate, &out.EnableDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MFADevice.
func (in *MFADevice) DeepCopy() *MFADevice {
	if in == nil {
		return nil
	}
	out := new(MFADevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPolicyDetail) DeepCopyInto(out *ManagedPolicyDetail) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.UpdateDate != nil {
		in, out := &in.UpdateDate, &out.UpdateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPolicyDetail.
func (in *ManagedPolicyDetail) DeepCopy() *ManagedPolicyDetail {
	if in == nil {
		return nil
	}
	out := new(ManagedPolicyDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDConnectProviderListEntry) DeepCopyInto(out *OpenIDConnectProviderListEntry) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDConnectProviderListEntry.
func (in *OpenIDConnectProviderListEntry) DeepCopy() *OpenIDConnectProviderListEntry {
	if in == nil {
		return nil
	}
	out := new(OpenIDConnectProviderListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UpdateDate != nil {
		in, out := &in.UpdateDate, &out.UpdateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDetail) DeepCopyInto(out *PolicyDetail) {
	*out = *in
	if in.PolicyDocument != nil {
		in, out := &in.PolicyDocument, &out.PolicyDocument
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDetail.
func (in *PolicyDetail) DeepCopy() *PolicyDetail {
	if in == nil {
		return nil
	}
	out := new(PolicyDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyGrantingServiceAccess) DeepCopyInto(out *PolicyGrantingServiceAccess) {
	*out = *in
	if in.PolicyARN != nil {
		in, out := &in.PolicyARN, &out.PolicyARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyGrantingServiceAccess.
func (in *PolicyGrantingServiceAccess) DeepCopy() *PolicyGrantingServiceAccess {
	if in == nil {
		return nil
	}
	out := new(PolicyGrantingServiceAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyGroup) DeepCopyInto(out *PolicyGroup) {
	*out = *in
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.GroupName != nil {
		in, out := &in.GroupName, &out.GroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyGroup.
func (in *PolicyGroup) DeepCopy() *PolicyGroup {
	if in == nil {
		return nil
	}
	out := new(PolicyGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRole) DeepCopyInto(out *PolicyRole) {
	*out = *in
	if in.RoleID != nil {
		in, out := &in.RoleID, &out.RoleID
		*out = new(string)
		**out = **in
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRole.
func (in *PolicyRole) DeepCopy() *PolicyRole {
	if in == nil {
		return nil
	}
	out := new(PolicyRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyUser) DeepCopyInto(out *PolicyUser) {
	*out = *in
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyUser.
func (in *PolicyUser) DeepCopy() *PolicyUser {
	if in == nil {
		return nil
	}
	out := new(PolicyUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyVersion) DeepCopyInto(out *PolicyVersion) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.Document != nil {
		in, out := &in.Document, &out.Document
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyVersion.
func (in *PolicyVersion) DeepCopy() *PolicyVersion {
	if in == nil {
		return nil
	}
	out := new(PolicyVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.AssumeRolePolicyDocument != nil {
		in, out := &in.AssumeRolePolicyDocument, &out.AssumeRolePolicyDocument
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MaxSessionDuration != nil {
		in, out := &in.MaxSessionDuration, &out.MaxSessionDuration
		*out = new(int64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundary != nil {
		in, out := &in.PermissionsBoundary, &out.PermissionsBoundary
		*out = new(AttachedPermissionsBoundary)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleID != nil {
		in, out := &in.RoleID, &out.RoleID
		*out = new(string)
		**out = **in
	}
	if in.RoleLastUsed != nil {
		in, out := &in.RoleLastUsed, &out.RoleLastUsed
		*out = new(RoleLastUsed)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDetail) DeepCopyInto(out *RoleDetail) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.AssumeRolePolicyDocument != nil {
		in, out := &in.AssumeRolePolicyDocument, &out.AssumeRolePolicyDocument
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundary != nil {
		in, out := &in.PermissionsBoundary, &out.PermissionsBoundary
		*out = new(AttachedPermissionsBoundary)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleID != nil {
		in, out := &in.RoleID, &out.RoleID
		*out = new(string)
		**out = **in
	}
	if in.RoleLastUsed != nil {
		in, out := &in.RoleLastUsed, &out.RoleLastUsed
		*out = new(RoleLastUsed)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDetail.
func (in *RoleDetail) DeepCopy() *RoleDetail {
	if in == nil {
		return nil
	}
	out := new(RoleDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleLastUsed) DeepCopyInto(out *RoleLastUsed) {
	*out = *in
	if in.LastUsedDate != nil {
		in, out := &in.LastUsedDate, &out.LastUsedDate
		*out = (*in).DeepCopy()
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleLastUsed.
func (in *RoleLastUsed) DeepCopy() *RoleLastUsed {
	if in == nil {
		return nil
	}
	out := new(RoleLastUsed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLProviderListEntry) DeepCopyInto(out *SAMLProviderListEntry) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLProviderListEntry.
func (in *SAMLProviderListEntry) DeepCopy() *SAMLProviderListEntry {
	if in == nil {
		return nil
	}
	out := new(SAMLProviderListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHPublicKey) DeepCopyInto(out *SSHPublicKey) {
	*out = *in
	if in.UploadDate != nil {
		in, out := &in.UploadDate, &out.UploadDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHPublicKey.
func (in *SSHPublicKey) DeepCopy() *SSHPublicKey {
	if in == nil {
		return nil
	}
	out := new(SSHPublicKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHPublicKeyMetadata) DeepCopyInto(out *SSHPublicKeyMetadata) {
	*out = *in
	if in.UploadDate != nil {
		in, out := &in.UploadDate, &out.UploadDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHPublicKeyMetadata.
func (in *SSHPublicKeyMetadata) DeepCopy() *SSHPublicKeyMetadata {
	if in == nil {
		return nil
	}
	out := new(SSHPublicKeyMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCertificate) DeepCopyInto(out *ServerCertificate) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCertificate.
func (in *ServerCertificate) DeepCopy() *ServerCertificate {
	if in == nil {
		return nil
	}
	out := new(ServerCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCertificateMetadata) DeepCopyInto(out *ServerCertificateMetadata) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = (*in).DeepCopy()
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.ServerCertificateID != nil {
		in, out := &in.ServerCertificateID, &out.ServerCertificateID
		*out = new(string)
		**out = **in
	}
	if in.UploadDate != nil {
		in, out := &in.UploadDate, &out.UploadDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCertificateMetadata.
func (in *ServerCertificateMetadata) DeepCopy() *ServerCertificateMetadata {
	if in == nil {
		return nil
	}
	out := new(ServerCertificateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLastAccessed) DeepCopyInto(out *ServiceLastAccessed) {
	*out = *in
	if in.LastAuthenticated != nil {
		in, out := &in.LastAuthenticated, &out.LastAuthenticated
		*out = (*in).DeepCopy()
	}
	if in.LastAuthenticatedEntity != nil {
		in, out := &in.LastAuthenticatedEntity, &out.LastAuthenticatedEntity
		*out = new(string)
		**out = **in
	}
	if in.LastAuthenticatedRegion != nil {
		in, out := &in.LastAuthenticatedRegion, &out.LastAuthenticatedRegion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLastAccessed.
func (in *ServiceLastAccessed) DeepCopy() *ServiceLastAccessed {
	if in == nil {
		return nil
	}
	out := new(ServiceLastAccessed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRole) DeepCopyInto(out *ServiceLinkedRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRole.
func (in *ServiceLinkedRole) DeepCopy() *ServiceLinkedRole {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceLinkedRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRoleList) DeepCopyInto(out *ServiceLinkedRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceLinkedRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRoleList.
func (in *ServiceLinkedRoleList) DeepCopy() *ServiceLinkedRoleList {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceLinkedRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRoleObservation) DeepCopyInto(out *ServiceLinkedRoleObservation) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.AssumeRolePolicyDocument != nil {
		in, out := &in.AssumeRolePolicyDocument, &out.AssumeRolePolicyDocument
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.MaxSessionDuration != nil {
		in, out := &in.MaxSessionDuration, &out.MaxSessionDuration
		*out = new(int64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundary != nil {
		in, out := &in.PermissionsBoundary, &out.PermissionsBoundary
		*out = new(AttachedPermissionsBoundary)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleID != nil {
		in, out := &in.RoleID, &out.RoleID
		*out = new(string)
		**out = **in
	}
	if in.RoleLastUsed != nil {
		in, out := &in.RoleLastUsed, &out.RoleLastUsed
		*out = new(RoleLastUsed)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRoleObservation.
func (in *ServiceLinkedRoleObservation) DeepCopy() *ServiceLinkedRoleObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRoleParameters) DeepCopyInto(out *ServiceLinkedRoleParameters) {
	*out = *in
	if in.AWSServiceName != nil {
		in, out := &in.AWSServiceName, &out.AWSServiceName
		*out = new(string)
		**out = **in
	}
	if in.CustomSuffix != nil {
		in, out := &in.CustomSuffix, &out.CustomSuffix
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	out.CustomServiceLinkedRoleParameters = in.CustomServiceLinkedRoleParameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRoleParameters.
func (in *ServiceLinkedRoleParameters) DeepCopy() *ServiceLinkedRoleParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRoleSpec) DeepCopyInto(out *ServiceLinkedRoleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRoleSpec.
func (in *ServiceLinkedRoleSpec) DeepCopy() *ServiceLinkedRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLinkedRoleStatus) DeepCopyInto(out *ServiceLinkedRoleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLinkedRoleStatus.
func (in *ServiceLinkedRoleStatus) DeepCopy() *ServiceLinkedRoleStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceLinkedRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecificCredential) DeepCopyInto(out *ServiceSpecificCredential) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecificCredential.
func (in *ServiceSpecificCredential) DeepCopy() *ServiceSpecificCredential {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecificCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecificCredentialMetadata) DeepCopyInto(out *ServiceSpecificCredentialMetadata) {
	*out = *in
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecificCredentialMetadata.
func (in *ServiceSpecificCredentialMetadata) DeepCopy() *ServiceSpecificCredentialMetadata {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecificCredentialMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningCertificate) DeepCopyInto(out *SigningCertificate) {
	*out = *in
	if in.UploadDate != nil {
		in, out := &in.UploadDate, &out.UploadDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningCertificate.
func (in *SigningCertificate) DeepCopy() *SigningCertificate {
	if in == nil {
		return nil
	}
	out := new(SigningCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedActionLastAccessed) DeepCopyInto(out *TrackedActionLastAccessed) {
	*out = *in
	if in.ActionName != nil {
		in, out := &in.ActionName, &out.ActionName
		*out = new(string)
		**out = **in
	}
	if in.LastAccessedEntity != nil {
		in, out := &in.LastAccessedEntity, &out.LastAccessedEntity
		*out = new(string)
		**out = **in
	}
	if in.LastAccessedRegion != nil {
		in, out := &in.LastAccessedRegion, &out.LastAccessedRegion
		*out = new(string)
		**out = **in
	}
	if in.LastAccessedTime != nil {
		in, out := &in.LastAccessedTime, &out.LastAccessedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedActionLastAccessed.
func (in *TrackedActionLastAccessed) DeepCopy() *TrackedActionLastAccessed {
	if in == nil {
		return nil
	}
	out := new(TrackedActionLastAccessed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.PasswordLastUsed != nil {
		in, out := &in.PasswordLastUsed, &out.PasswordLastUsed
		*out = (*in).DeepCopy()
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundary != nil {
		in, out := &in.PermissionsBoundary, &out.PermissionsBoundary
		*out = new(AttachedPermissionsBoundary)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDetail) DeepCopyInto(out *UserDetail) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = (*in).DeepCopy()
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PermissionsBoundary != nil {
		in, out := &in.PermissionsBoundary, &out.PermissionsBoundary
		*out = new(AttachedPermissionsBoundary)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDetail.
func (in *UserDetail) DeepCopy() *UserDetail {
	if in == nil {
		return nil
	}
	out := new(UserDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMFADevice) DeepCopyInto(out *VirtualMFADevice) {
	*out = *in
	if in.EnableDate != nil {
		in, out := &in.EnableDate, &out.EnableDate
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMFADevice.
func (in *VirtualMFADevice) DeepCopy() *VirtualMFADevice {
	if in == nil {
		return nil
	}
	out := new(VirtualMFADevice)
	in.DeepCopyInto(out)
	return out
}
