/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package firewallpolicy

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/networkfirewall"
	svcsdk "github.com/aws/aws-sdk-go/service/networkfirewall"
	svcsdkapi "github.com/aws/aws-sdk-go/service/networkfirewall/networkfirewalliface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/networkfirewall/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an FirewallPolicy resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create FirewallPolicy in AWS"
	errUpdate        = "cannot update FirewallPolicy in AWS"
	errDescribe      = "failed to describe FirewallPolicy"
	errDelete        = "failed to delete FirewallPolicy"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.FirewallPolicy)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.FirewallPolicy)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeFirewallPolicyInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeFirewallPolicyWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateFirewallPolicy(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.FirewallPolicy)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateFirewallPolicyInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateFirewallPolicyWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.FirewallPolicyResponse != nil {
		f0 := &svcapitypes.FirewallPolicyResponse{}
		if resp.FirewallPolicyResponse.Description != nil {
			f0.Description = resp.FirewallPolicyResponse.Description
		}
		if resp.FirewallPolicyResponse.FirewallPolicyArn != nil {
			f0.FirewallPolicyARN = resp.FirewallPolicyResponse.FirewallPolicyArn
		}
		if resp.FirewallPolicyResponse.FirewallPolicyId != nil {
			f0.FirewallPolicyID = resp.FirewallPolicyResponse.FirewallPolicyId
		}
		if resp.FirewallPolicyResponse.FirewallPolicyName != nil {
			f0.FirewallPolicyName = resp.FirewallPolicyResponse.FirewallPolicyName
		}
		if resp.FirewallPolicyResponse.FirewallPolicyStatus != nil {
			f0.FirewallPolicyStatus = resp.FirewallPolicyResponse.FirewallPolicyStatus
		}
		if resp.FirewallPolicyResponse.Tags != nil {
			f0f5 := []*svcapitypes.Tag{}
			for _, f0f5iter := range resp.FirewallPolicyResponse.Tags {
				f0f5elem := &svcapitypes.Tag{}
				if f0f5iter.Key != nil {
					f0f5elem.Key = f0f5iter.Key
				}
				if f0f5iter.Value != nil {
					f0f5elem.Value = f0f5iter.Value
				}
				f0f5 = append(f0f5, f0f5elem)
			}
			f0.Tags = f0f5
		}
		cr.Status.AtProvider.FirewallPolicyResponse = f0
	} else {
		cr.Status.AtProvider.FirewallPolicyResponse = nil
	}
	if resp.UpdateToken != nil {
		cr.Status.AtProvider.UpdateToken = resp.UpdateToken
	} else {
		cr.Status.AtProvider.UpdateToken = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*svcapitypes.FirewallPolicy)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	input := GenerateUpdateFirewallPolicyInput(cr)
	if err := e.preUpdate(ctx, cr, input); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.UpdateFirewallPolicyWithContext(ctx, input)
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, awsclient.Wrap(err, errUpdate))
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.FirewallPolicy)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteFirewallPolicyInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteFirewallPolicyWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.NetworkFirewallAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.NetworkFirewallAPI
	preObserve     func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DescribeFirewallPolicyInput) error
	postObserve    func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DescribeFirewallPolicyOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.FirewallPolicyParameters, *svcsdk.DescribeFirewallPolicyOutput) error
	isUpToDate     func(*svcapitypes.FirewallPolicy, *svcsdk.DescribeFirewallPolicyOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.CreateFirewallPolicyInput) error
	postCreate     func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.CreateFirewallPolicyOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DeleteFirewallPolicyInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DeleteFirewallPolicyOutput, error) error
	preUpdate      func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.UpdateFirewallPolicyInput) error
	postUpdate     func(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.UpdateFirewallPolicyOutput, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DescribeFirewallPolicyInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.FirewallPolicy, _ *svcsdk.DescribeFirewallPolicyOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.FirewallPolicyParameters, *svcsdk.DescribeFirewallPolicyOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.FirewallPolicy, *svcsdk.DescribeFirewallPolicyOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.CreateFirewallPolicyInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.FirewallPolicy, _ *svcsdk.CreateFirewallPolicyOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.DeleteFirewallPolicyInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.FirewallPolicy, _ *svcsdk.DeleteFirewallPolicyOutput, err error) error {
	return err
}
func nopPreUpdate(context.Context, *svcapitypes.FirewallPolicy, *svcsdk.UpdateFirewallPolicyInput) error {
	return nil
}
func nopPostUpdate(_ context.Context, _ *svcapitypes.FirewallPolicy, _ *svcsdk.UpdateFirewallPolicyOutput, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	return upd, err
}
