/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AttachmentStatus string

const (
	AttachmentStatus_CREATING AttachmentStatus = "CREATING"
	AttachmentStatus_DELETING AttachmentStatus = "DELETING"
	AttachmentStatus_SCALING  AttachmentStatus = "SCALING"
	AttachmentStatus_READY    AttachmentStatus = "READY"
)

type ConfigurationSyncState string

const (
	ConfigurationSyncState_PENDING ConfigurationSyncState = "PENDING"
	ConfigurationSyncState_IN_SYNC ConfigurationSyncState = "IN_SYNC"
)

type FirewallStatusValue string

const (
	FirewallStatusValue_PROVISIONING FirewallStatusValue = "PROVISIONING"
	FirewallStatusValue_DELETING     FirewallStatusValue = "DELETING"
	FirewallStatusValue_READY        FirewallStatusValue = "READY"
)

type GeneratedRulesType string

const (
	GeneratedRulesType_ALLOWLIST GeneratedRulesType = "ALLOWLIST"
	GeneratedRulesType_DENYLIST  GeneratedRulesType = "DENYLIST"
)

type LogDestinationType string

const (
	LogDestinationType_S3                  LogDestinationType = "S3"
	LogDestinationType_CloudWatchLogs      LogDestinationType = "CloudWatchLogs"
	LogDestinationType_KinesisDataFirehose LogDestinationType = "KinesisDataFirehose"
)

type LogType string

const (
	LogType_ALERT LogType = "ALERT"
	LogType_FLOW  LogType = "FLOW"
)

type PerObjectSyncStatus string

const (
	PerObjectSyncStatus_PENDING PerObjectSyncStatus = "PENDING"
	PerObjectSyncStatus_IN_SYNC PerObjectSyncStatus = "IN_SYNC"
)

type ResourceStatus string

const (
	ResourceStatus_ACTIVE   ResourceStatus = "ACTIVE"
	ResourceStatus_DELETING ResourceStatus = "DELETING"
)

type RuleGroupType string

const (
	RuleGroupType_STATELESS RuleGroupType = "STATELESS"
	RuleGroupType_STATEFUL  RuleGroupType = "STATEFUL"
)

type StatefulAction string

const (
	StatefulAction_PASS  StatefulAction = "PASS"
	StatefulAction_DROP  StatefulAction = "DROP"
	StatefulAction_ALERT StatefulAction = "ALERT"
)

type StatefulRuleDirection string

const (
	StatefulRuleDirection_FORWARD StatefulRuleDirection = "FORWARD"
	StatefulRuleDirection_ANY     StatefulRuleDirection = "ANY"
)

type StatefulRuleProtocol string

const (
	StatefulRuleProtocol_IP     StatefulRuleProtocol = "IP"
	StatefulRuleProtocol_TCP    StatefulRuleProtocol = "TCP"
	StatefulRuleProtocol_UDP    StatefulRuleProtocol = "UDP"
	StatefulRuleProtocol_ICMP   StatefulRuleProtocol = "ICMP"
	StatefulRuleProtocol_HTTP   StatefulRuleProtocol = "HTTP"
	StatefulRuleProtocol_FTP    StatefulRuleProtocol = "FTP"
	StatefulRuleProtocol_TLS    StatefulRuleProtocol = "TLS"
	StatefulRuleProtocol_SMB    StatefulRuleProtocol = "SMB"
	StatefulRuleProtocol_DNS    StatefulRuleProtocol = "DNS"
	StatefulRuleProtocol_DCERPC StatefulRuleProtocol = "DCERPC"
	StatefulRuleProtocol_SSH    StatefulRuleProtocol = "SSH"
	StatefulRuleProtocol_SMTP   StatefulRuleProtocol = "SMTP"
	StatefulRuleProtocol_IMAP   StatefulRuleProtocol = "IMAP"
	StatefulRuleProtocol_MSN    StatefulRuleProtocol = "MSN"
	StatefulRuleProtocol_KRB5   StatefulRuleProtocol = "KRB5"
	StatefulRuleProtocol_IKEV2  StatefulRuleProtocol = "IKEV2"
	StatefulRuleProtocol_TFTP   StatefulRuleProtocol = "TFTP"
	StatefulRuleProtocol_NTP    StatefulRuleProtocol = "NTP"
	StatefulRuleProtocol_DHCP   StatefulRuleProtocol = "DHCP"
)

type TCPFlag string

const (
	TCPFlag_FIN TCPFlag = "FIN"
	TCPFlag_SYN TCPFlag = "SYN"
	TCPFlag_RST TCPFlag = "RST"
	TCPFlag_PSH TCPFlag = "PSH"
	TCPFlag_ACK TCPFlag = "ACK"
	TCPFlag_URG TCPFlag = "URG"
	TCPFlag_ECE TCPFlag = "ECE"
	TCPFlag_CWR TCPFlag = "CWR"
)

type TargetType string

const (
	TargetType_TLS_SNI   TargetType = "TLS_SNI"
	TargetType_HTTP_HOST TargetType = "HTTP_HOST"
)
